I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 547, in script
    a2 "AYE!"
Exception: Sayer 'a2' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 547, in script
    a2 "AYE!"
  File "C:\Users\fayef\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\fayef\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'a2' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Trick 1.0
Sun Oct 30 04:25:39 2022
